# Generated by Django 5.2.11 on 2026-02-22 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('safety_score', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lon', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.FloatField(default=0.0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('risky_count', models.IntegerField(default=0)),
                ('avg_severity', models.FloatField(default=0.0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='api.location')),
            ],
        ),
    ]
